version: "3.8"

services:
  registry:
    container_name: registry
    image: registry:2.8.1
    restart: always
    ports:
      - ${PORT}:5000
    volumes:
      - registry_data:/var/lib/registry
      - ./auth:/auth
    environment:
      REGISTRY_AUTH: htpasswd
      REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
      REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
    networks:
      - https

volumes:
  registry_data:
    name: registry_data

networks:
  https:
    name: ${HTTPS_NETWORK}
    external: true 
